name: Continuous Integration


on:
  push:
    branches: [master, develop, release/**]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      triggeredBy:
        description: 'Name of team member who is manually triggering this workflow'
        required: true

defaults:
  run:
    shell: bash

env:
  LANG: en_US.utf-8
  LC_ALL: en_US.utf-8

jobs:

  run-tests:

    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12, windows-2022]
        python: ['3.8', '3.9', '3.10', '3.11']

    runs-on: ${{ matrix.os }}

    steps:

    - run: |
        echo "This workflow was triggered by: $TRIGGER_PERSON"
      env:
        TRIGGER_PERSON: ${{ inputs.triggeredBy }}
    - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
    - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
    - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}

    - name: Install Pylint
      run: pip install pylint

    # https://github.com/pre-commit/action
    - name: Run pre-commit hooks
      uses: pre-commit/action@v3.0.0

    - name: Run tests
      run: |
        make test-ci-github
